#!/bin/gnu/make

#
#	Standard file manipulation library for cell language
#	Copyright (c) Armands Arseniuss Skolmeisters, All rights reserved.
#
#	This library is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public
#	License as published by the Free Software Foundation; either
#	version 3.0 of the License, or (at your option) any later version.
#
#	This library is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#	Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this library.
#

NAME		= std.file

include config.mk

LIBS		= \
		    os \
		    os.$(HOST) \
		    cell.builtin

SRCS		= \
		    csource/file.c

HDRS		= \
		    include/cell/std/file.h

include scripts/libs.base.mk


