#!/bin/gnu/make

#
#	Cell language token library
#	Copyright (c) Armands Arseniuss Skolmeisters, All rights reserved.
#
#	This library is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public
#	License as published by the Free Software Foundation; either
#	version 3.0 of the License, or (at your option) any later version.
#
#	This library is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#	Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this library.
#

NAME		= libcell/libcell.token

include libs.mk

HDRS		= \
		    include/cell/lang/source.h \
		    include/cell/lang/target.h \
		    include/cell/lang/token.h \
		    include/cell/lang/tokens.inc.h
	
SRCS		= \
		    csource/source.c \
		    csource/tokens.c


include /source/scripts/libs.base.mk
