function arch-make-config() {
    local arch="$1"
    local target="$2"
    local cflags="$3"
    
    mkdir -p $ROOT/$arch/config/gnu/make/
    
    cat <<END > $ROOT/$arch/config/gnu/make/arch.mk
# This file autogenerated by $0 script
# Do not edit it manually

CFLAGS += \\
    -D __ARCH__=$arch \\
    -target $target $3
    
LDFLAGS +=
END
}

echo "This script creates architecture dependent configuration"

if [ -z $ROOT ]; then
    echo ROOT is empty
    exit 1
fi

arch-make-config x86_64  x86_64-unknown-flos-elf
arch-make-config arm64  aarch64-unknown-flos-elf
arch-make-config armel  arm-unknown-flos-eabi
arch-make-config armhf  arm-unknown-flos-eabi       -mfloat-abi=hard
arch-make-config mips   mips-unknown-flos-elf
arch-make-config mipsel mipsel-unknown-flos-elf
arch-make-config x86    i386-unknown-flos-elf
