/**
 *  Linux layer library
 *  Copyright (C) 2018 - 2019  Armands Arseniuss Skolmeisters
 *
 *  This library is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef F
#    define F(x, y, z)
#endif


F(EPERM, 1, "Operation not permitted")
    F(ENOENT, 2, "No such file or directory")
    F(ESRCH, 3, "No such process")
    F(EINTR, 4, "Interrupted system call")
    F(EIO, 5, "I/O error")
    F(ENXIO, 6, "No such device or address")
    F(E2BIG, 7, "Argument list too long")
    F(ENOEXEC, 8, "Exec format error")
    F(EBADF, 9, "Bad file number")
    F(ECHILD, 10, "No child processes")
    F(EAGAIN, 11, "Try again")
    F(ENOMEM, 12, "Out of memory")
    F(EACCES, 13, "Permission denied")
    F(EFAULT, 14, "Bad address")
    F(ENOTBLK, 15, "Block device required")
    F(EBUSY, 16, "Device or resource busy")
    F(EEXIST, 17, "File exists")
    F(EXDEV, 18, "Cross-device link")
    F(ENODEV, 19, "No such device")
    F(ENOTDIR, 20, "Not a directory")
    F(EISDIR, 21, "Is a directory")
    F(EINVAL, 22, "Invalid argument")
    F(ENFILE, 23, "File table overflow")
    F(EMFILE, 24, "Too many open files")
    F(ENOTTY, 25, "Not a typewriter")
    F(ETXTBSY, 26, "Text file busy")
    F(EFBIG, 27, "File too large")
    F(ENOSPC, 28, "No space left on device")
    F(ESPIPE, 29, "Illegal seek")
    F(EROFS, 30, "Read-only file system")
    F(EMLINK, 31, "Too many links")
    F(EPIPE, 32, "Broken pipe")
    F(EDOM, 33, "Math argument out of domain of func")
    F(ERANGE, 34, "Math result not representable")
    F(EDEADLK, 35, "Resource deadlock would occur")
    F(ENAMETOOLONG, 36, "File name too long")
    F(ENOLCK, 37, "No record locks available")
    F(ENOSYS, 38, "Function not implemented")
    F(ENOTEMPTY, 39, "Directory not empty")
    F(ELOOP, 40, "Too many symbolic links encountered")
#ifndef UNIQUE
    F(EWOULDBLOCK, 11, "Operation would block")
#else
    F(EWOULDBLOCK, 41, "(Invalid) Operation would block")
#endif
    F(ENOMSG, 42, "No message of desired type")
    F(EIDRM, 43, "Identifier removed")
    F(ECHRNG, 44, "Channel number out of range")
    F(EL2NSYNC, 45, "Level 2 not synchronized")
    F(EL3HLT, 46, "Level 3 halted")
    F(EL3RST, 47, "Level 3 reset")
    F(ELNRNG, 48, "Link number out of range")
    F(EUNATCH, 49, "Protocol driver not attached")
    F(ENOCSI, 50, "No CSI structure available")
    F(EL2HLT, 51, "Level 2 halted")
    F(EBADE, 52, "Invalid exchange")
    F(EBADR, 53, "Invalid request descriptor")
    F(EXFULL, 54, "Exchange full")
    F(ENOANO, 55, "No anode")
    F(EBADRQC, 56, "Invalid request code")
    F(EBADSLT, 57, "Invalid slot")
#ifndef UNIQUE
    F(EDEADLOCK, 35, "Deadlock")
#else
    F(EDEADLOCK, 58, "(Invalid) Deadlock")
#endif
    F(EBFONT, 59, "Bad font file format")
    F(ENOSTR, 60, "Device not a stream")
    F(ENODATA, 61, "No data available")
    F(ETIME, 62, "Timer expired")
    F(ENOSR, 63, "Out of streams resources")
    F(ENONET, 64, "Machine is not on the network")
    F(ENOPKG, 65, "Package not installed")
    F(EREMOTE, 66, "Object is remote")
    F(ENOLINK, 67, "Link has been severed")
    F(EADV, 68, "Advertise error")
    F(ESRMNT, 69, "Srmount error")
    F(ECOMM, 70, "Communication error on send")
    F(EPROTO, 71, "Protocol error")
    F(EMULTIHOP, 72, "Multihop attempted")
    F(EDOTDOT, 73, "RFS specific error")
    F(EBADMSG, 74, "Not a data message")
    F(EOVERFLOW, 75, "Value too large for defined data type")
    F(ENOTUNIQ, 76, "Name not unique on network")
    F(EBADFD, 77, "File descriptor in bad state")
    F(EREMCHG, 78, "Remote address changed")
    F(ELIBACC, 79, "Can not access a needed shared library")
    F(ELIBBAD, 80, "Accessing a corrupted shared library")
    F(ELIBSCN, 81, ".lib section in a.out corrupted")
    F(ELIBMAX, 82, "Attempting to link in too many shared libraries")
    F(ELIBEXEC, 83, "Cannot exec a shared library directly")
    F(EILSEQ, 84, "Illegal byte sequence")
    F(ERESTART, 85, "Interrupted system call should be restarted")
    F(ESTRPIPE, 86, "Streams pipe error")
    F(EUSERS, 87, "Too many users")
    F(ENOTSOCK, 88, "Socket operation on non-socket")
    F(EDESTADDRREQ, 89, "Destination address required")
    F(EMSGSIZE, 90, "Message too long")
    F(EPROTOTYPE, 91, "Protocol wrong type for socket")
    F(ENOPROTOOPT, 92, "Protocol not available")
    F(EPROTONOSUPPORT, 93, "Protocol not supported")
    F(ESOCKTNOSUPPORT, 94, "Socket type not supported")
    F(EOPNOTSUPP, 95, "Operation not supported on transport endpoint")
    F(EPFNOSUPPORT, 96, "Protocol family not supported")
    F(EAFNOSUPPORT, 97, "Address family not supported by protocol")
    F(EADDRINUSE, 98, "Address already in use")
    F(EADDRNOTAVAIL, 99, "Cannot assign requested address")
    F(ENETDOWN, 100, "Network is down")
    F(ENETUNREACH, 101, "Network is unreachable")
    F(ENETRESET, 102, "Network dropped connection because of reset")
    F(ECONNABORTED, 103, "Software caused connection abort")
    F(ECONNRESET, 104, "Connection reset by peer")
    F(ENOBUFS, 105, "No buffer space available")
    F(EISCONN, 106, "Transport endpoint is already connected")
    F(ENOTCONN, 107, "Transport endpoint is not connected")
    F(ESHUTDOWN, 108, "Cannot send after transport endpoint shutdown")
    F(ETOOMANYREFS, 109, "Too many references: cannot splice")
    F(ETIMEDOUT, 110, "Connection timed out")
    F(ECONNREFUSED, 111, "Connection refused")
    F(EHOSTDOWN, 112, "Host is down")
    F(EHOSTUNREACH, 113, "No route to host")
    F(EALREADY, 114, "Operation already in progress")
    F(EINPROGRESS, 115, "Operation now in progress")
    F(ESTALE, 116, "Stale NFS file handle")
    F(EUCLEAN, 117, "Structure needs cleaning")
    F(ENOTNAM, 118, "Not a XENIX named type file")
    F(ENAVAIL, 119, "No XENIX semaphores available")
    F(EISNAM, 120, "Is a named type file")
    F(EREMOTEIO, 121, "Remote I/O error")
    F(EDQUOT, 122, "Quota exceeded")

    F(ENOMEDIUM, 123, "No medium found")
    F(EMEDIUMTYPE, 124, "Wrong medium type")
    F(ECANCELED, 125, "Operation Canceled")
    F(ENOKEY, 126, "Required key not available")
    F(EKEYEXPIRED, 127, "Key has expired")
    F(EKEYREVOKED, 128, "Key has been revoked")
    F(EKEYREJECTED, 129, "Key was rejected by service")


    F(EOWNERDEAD, 130, "Owner died")
    F(ENOTRECOVERABLE, 131, "State not recoverable")
