ifeq ($(ROOT),)
$(error ROOT is not defined!)
endif

MKFILES = \
	cell/makefile \
	core/makefile \
	libarchive/makefile \
	libcompress/makefile \
	libcrypto/makefile \
	libos/makefile \
	libreflect/makefile \
	libstd/makefile \
	pkg/makefile \
	shell/makefile

include $(ROOT)/source/config/make/arch.mk
